### ISSUE TITLE
Rgaa 3 - 8.9.1 : fieldset without a form element

### ISSUE THREAD

**Issue by armonyaltinier** [Asqatasun/Asqatasun#104]
## Observed behavior

A fieldset without a form element → marks the 8.9.1 test as Failed
## Expected behavior

Mark the 8.9.1 as Pre-qualified, not failed. It is not forbidden to use a fieldset without a form element.

**Comment by mfaure** [comment]
OK, I dug at least one hour in the:

* [fieldset definition in HTML 5](https://www.w3.org/TR/html5/forms.html#the-fieldset-element)
* and in the [fieldset definition in HTML 5.1](http://w3c.github.io/html/sec-forms.html#the-fieldset-element) 
* and also in [fieldset definition in HTML 4.01](https://www.w3.org/TR/html401/interact/forms.html#h-17.10).

I found nothing claiming the obligation to have a form associated to a fieldset. So, you're right, this should be a warning :) Fix in progress

**Comment by mfaure** [comment]
OK Fixed in a dedicated branch (that will be merged to Develop). Unit tests from our testcases are OK. @armonyaltinier any real life example to complete testing ?

**Comment by mfaure** [comment]
@armonyaltinier OK this is fixed since 99786f9cc4e44ed8947ae7b2ba608fc8f59a49b2
You may test it immediately and easily thanks to the brand new ["SNAPSHOT" docker image](http://forum.asqatasun.org/t/new-docker-image-for-develop-branch/114), that gives you a Docker Image based on `develop` branch.
You may also review the [testcase files for 8.9.1](https://github.com/Asqatasun/Asqatasun/tree/develop/rules/rules-rgaa3.0/src/test/resources/testcases/rgaa30/Rgaa30Rule080901), especially the `-05`, `-06`, `-07` ones.

**Comment by mfaure** [comment]
@armonyaltinier I reconsider and enhance my position on that matter :) Let's consider: 

1. a `div` 
1. without `role=form` or `role=search`
1. containing a `fieldset`
1. (and without any `form` between the `div` and the `fieldset`)

... that is:

```html
<div>
  <fieldset>
    <p>Oh nice, my paragraph is graphically surrounded by a nice sweet border!</p>
  </fieldset>
</div>
```

Do you agree that this should return FAILED for this test 8.9.1 ?

(while waiting for your answer I reopen this issue)

**Comment by dzc34** [comment]
Closed as we've moved to gitlab https://gitlab.com/asqatasun/Asqatasun
