### ISSUE TITLE
Admin user can change the email of all users, but not his own email address.

### ISSUE THREAD

**Issue by mgifford** [Asqatasun/Asqatasun#214]
## Observed behaviour

I can't seem to change the email address in my Docker instance. Despite the success message, my email still is "`me@my-email.org`".

<img width="933" alt="screen shot 2018-04-03 at 8 41 45 am" src="https://user-images.githubusercontent.com/116832/38249805-e6db40e4-371a-11e8-8570-961d6520e2d9.png">

## Expected behaviour

If I edit a user account's email addres, it should change.

## Steps to reproduce the behaviour

Go here and change the email address:
`http://localhost:8080/asqatasun/admin/edit-user.html?user=1`

## Your configuration

Default Docker

* Asqatasun version (in the footer of any webpage) -->  Asqatasun v4.0.3 -
* Using Docker image ? --> Yes

**Comment by dzc34** [comment]
@mgifford, I reproduce the bug.

- In "User account settings > My details", no one can change their own e-mail. This is indicated by the message "This address has to be used to access the service. You cannot modify it."
- In "Administration > Edit the user xx@xxx.xx", admin user can change the email of all users, but not his own email address. I think the bug is here.

Administration

**Comment by dzc34** [comment]
@mgifford, in fact, it's not a _bug_ but a _feature_! @mfaure explained to me that this is the easy solution to prevent an admin user from locking himself out of the application.
