### ISSUE TITLE
Proxy and access issue from corporate environment

### ISSUE THREAD

**Issue by softwareklinic** [Asqatasun/Asqatasun#75]
Hello,

Im trying to setup proxy for asqatasun.conf so as it can crawl and test pages from behind proxy... I need to understand where do i need to make the changes..

i added proxy host to /etc/asqatasun/asqatasun.conf as proxyhost=http://proxy.xxxx.xxxx.con:80/

Also, i tried using separate URL and PORT into 2 different variables - but is leading me to error page

A problem occured while loading the content of the page.

URL: http://www.google.com
Date: February 20, 2016 2:37:28 PM
Possible causes
Either the page doesn't exist
Either the page doesn't respond in less than 20 secondes
Either the page requires authentication
Or a modal dialog is present

**Comment by jkowalczyk** [comment]
Hi, 

You have dedicated properties in the asqatasun.conf file : 
`
proxyHost=
proxyPort=
proxyUser=
proxyPassword=
proxyExclusionUrl=
`

You need to use them to make it mork.

I suggest you to set the DEBUG level to get more trace in case of failure. 

You have a last way to deal with errors when settting proxy. You can set the 'bypassUrlCheck' property to true and thus  bypass the initial check of URL before effective launch of audit (as it is written in the comments).

BTW, don't hesitate to use the [forum](http://forum.asqatasun.org)  instead of github when you have questions. This is what it is made for.

Regards 

Koj

**Comment by mfaure** [comment]
I close this issue as it is more relative to the user discussion in the [Asqatasun forum](http://forum.asqatasun.org/).
